spring:
  application.name: app
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    password: password
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8081