services:
  database:
    image: mysql:latest
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - shared

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - shared

networks:
  shared: